### PR TITLE
Create ko_kr.json

### PR DESCRIPTION
**Pull request by othuntgithub**
Added Korean translation for Ars Nouveau.

Ars Nouveau 모드를 위한 한국어 번역을 추가하였습니다.

### CODE REVIEW

**Comment by baileyholl** [comment]
Two more translations have been added in the latest PR if you would like to catch those as well, ill merge before the next release, thank you!

**Comment by othuntgithub** [comment]
> Two more translations have been added in the latest PR if you would like to catch those as well, ill merge before the next release, thank you!

I did them all, thanks!

**Comment by baileyholl** [comment]
I have also added the missing langs for the spell names in the spell book, and the spell descriptions in the patchouli book.

**Comment by othuntgithub** [comment]
> I have also added the missing langs for the spell names in the spell book, and the spell descriptions in the patchouli book.

Thank you for improvement!

**Pull request merged**
