### PR TITLE
Overhaul Chinese translation

### PR DESCRIPTION
**Pull request by kappa-maintainer**
To make guidebook's landing text and information in glyph recipe localizable, I modified book.json and GlyphPressProcessor.java.

### CODE REVIEW

**Comment by kappa-maintainer** [comment]
Please notify me when all new strings are added. I will solve the conflict and fully translate them.

**Comment by baileyholl** [comment]
Will do, thanks!

**Comment by kappa-maintainer** [comment]
Done.

**Comment by baileyholl** [comment]
I think that is all of the lang changes I have for now until the next major release.

**Comment by kappa-maintainer** [comment]
My translation has updated to the latest change, so you may merge now. You may also want to check those new translation keys of tooltip since I am not good at naming them...

**Pull request merged**
